# Generated by Django 4.0.6 on 2022-08-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_evento',
            field=models.CharField(max_length=5),
        ),
    ]
