# Generated by Django 4.0.6 on 2022-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_evento_autor_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asistencias_evento',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
