# Generated by Django 4.0.6 on 2022-08-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciausuario',
            name='id_usuario_asiste',
            field=models.BooleanField(default=False),
        ),
    ]
