# Generated by Django 4.0.6 on 2022-08-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_asistenciausuario_id_usuario_asiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefono_usuario',
        ),
    ]
